version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 598598421932.dkr.ecr.us-west-1.amazonaws.com
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - mvn clean package -Ddockerfile.skip
    - docker build -t $IMAGE_URI .
    - docker image ls
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo $IMAGE_URI
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
